//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTuner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTuner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes is a trademark of Apple Inc..
        /// </summary>
        public static string AboutBox_Apple {
            get {
                return ResourceManager.GetString("AboutBox_Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new releases.
        /// </summary>
        public static string AboutBox_Check {
            get {
                return ResourceManager.GetString("AboutBox_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} {1}.
        /// </summary>
        public static string AboutBox_Copyright {
            get {
                return ResourceManager.GetString("AboutBox_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string AboutBox_Reserved {
            get {
                return ResourceManager.GetString("AboutBox_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string ActionMute {
            get {
                return ResourceManager.GetString("ActionMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string ActionNextTrack {
            get {
                return ResourceManager.GetString("ActionNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string ActionPlayPause {
            get {
                return ResourceManager.GetString("ActionPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        public static string ActionPrevTrack {
            get {
                return ResourceManager.GetString("ActionPrevTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show iTuner.
        /// </summary>
        public static string ActionShowiTuner {
            get {
                return ResourceManager.GetString("ActionShowiTuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show iTunes.
        /// </summary>
        public static string ActionShowiTunes {
            get {
                return ResourceManager.GetString("ActionShowiTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Lyrics.
        /// </summary>
        public static string ActionShowLyrics {
            get {
                return ResourceManager.GetString("ActionShowLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        public static string ActionVolumeDown {
            get {
                return ResourceManager.GetString("ActionVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        public static string ActionVolumeUp {
            get {
                return ResourceManager.GetString("ActionVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Album {
            get {
                object obj = ResourceManager.GetObject("Album", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Artist {
            get {
                object obj = ResourceManager.GetObject("Artist", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string ControlPanel_NextTrack {
            get {
                return ResourceManager.GetString("ControlPanel_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string ControlPanel_PlayPause {
            get {
                return ResourceManager.GetString("ControlPanel_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        public static string ControlPanel_PrevTrack {
            get {
                return ResourceManager.GetString("ControlPanel_PrevTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string DeviceSelector_Album {
            get {
                return ResourceManager.GetString("DeviceSelector_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string DeviceSelector_Artist {
            get {
                return ResourceManager.GetString("DeviceSelector_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached USB MP3 Players.
        /// </summary>
        public static string DeviceSelector_Attached {
            get {
                return ResourceManager.GetString("DeviceSelector_Attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detect folder capabilities.
        /// </summary>
        public static string DeviceSelector_AutoDetect {
            get {
                return ResourceManager.GetString("DeviceSelector_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive:.
        /// </summary>
        public static string DeviceSelector_Drive {
            get {
                return ResourceManager.GetString("DeviceSelector_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free space:.
        /// </summary>
        public static string DeviceSelector_Free {
            get {
                return ResourceManager.GetString("DeviceSelector_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string DeviceSelector_Genre {
            get {
                return ResourceManager.GetString("DeviceSelector_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout:.
        /// </summary>
        public static string DeviceSelector_Layout {
            get {
                return ResourceManager.GetString("DeviceSelector_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string DeviceSelector_Model {
            get {
                return ResourceManager.GetString("DeviceSelector_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string DeviceSelector_Playlist {
            get {
                return ResourceManager.GetString("DeviceSelector_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder:.
        /// </summary>
        public static string DeviceSelector_Target {
            get {
                return ResourceManager.GetString("DeviceSelector_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Title.
        /// </summary>
        public static string DeviceSelector_Title {
            get {
                return ResourceManager.GetString("DeviceSelector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Duplicates {
            get {
                object obj = ResourceManager.GetObject("Duplicates", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon EmptyDirectory {
            get {
                object obj = ResourceManager.GetObject("EmptyDirectory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encoding.
        /// </summary>
        public static string EncoderNone {
            get {
                return ResourceManager.GetString("EncoderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ExceptionDialog_CopyButton {
            get {
                return ResourceManager.GetString("ExceptionDialog_CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details....
        /// </summary>
        public static string ExceptionDialog_DetailsBlock {
            get {
                return ResourceManager.GetString("ExceptionDialog_DetailsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner Exception.
        /// </summary>
        public static string ExceptionDialog_Title {
            get {
                return ResourceManager.GetString("ExceptionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ExportCancelCaption {
            get {
                return ResourceManager.GetString("ExportCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export is in progress.
        ///Are you sure you want to cancel?.
        /// </summary>
        public static string ExportCancelText {
            get {
                return ResourceManager.GetString("ExportCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportDialog_ExportButton {
            get {
                return ResourceManager.GetString("ExportDialog_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        public static string ExportDialog_Exporting {
            get {
                return ResourceManager.GetString("ExportDialog_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export using:.
        /// </summary>
        public static string ExportDialog_ExportUsing {
            get {
                return ResourceManager.GetString("ExportDialog_ExportUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export location:.
        /// </summary>
        public static string ExportDialog_Location {
            get {
                return ResourceManager.GetString("ExportDialog_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create playlist without exporting media files.
        /// </summary>
        public static string ExportDialog_NoMedia {
            get {
                return ResourceManager.GetString("ExportDialog_NoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlist.
        /// </summary>
        public static string ExportDialog_NoPlaylist {
            get {
                return ResourceManager.GetString("ExportDialog_NoPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist format:.
        /// </summary>
        public static string ExportDialog_PlaylistFormat {
            get {
                return ResourceManager.GetString("ExportDialog_PlaylistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create artist/album sub-folders.
        /// </summary>
        public static string ExportDialog_SubFolders {
            get {
                return ResourceManager.GetString("ExportDialog_SubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner Export.
        /// </summary>
        public static string ExportDialog_Title {
            get {
                return ResourceManager.GetString("ExportDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the iTuner export location.
        /// </summary>
        public static string ExportFolderDialogDescription {
            get {
                return ResourceManager.GetString("ExportFolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0} tracks from album &apos;{1}&apos; by &apos;{2}&apos;.
        /// </summary>
        public static string ExportingAlbum {
            get {
                return ResourceManager.GetString("ExportingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0} tracks by artist &apos;{1}&apos;.
        /// </summary>
        public static string ExportingArtist {
            get {
                return ResourceManager.GetString("ExportingArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0} tracks.
        /// </summary>
        public static string ExportingCount {
            get {
                return ResourceManager.GetString("ExportingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0} tracks from playlist &apos;{1}&apos;.
        /// </summary>
        public static string ExportingPlaylist {
            get {
                return ResourceManager.GetString("ExportingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Warning.
        /// </summary>
        public static string ExportWarningDialogCaption {
            get {
                return ResourceManager.GetString("ExportWarningDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time to export {0} tracks is {1}. While this process runs you may still use iTunes and iTuner or stop the export at any time.
        ///
        ///Do you want to continue?.
        /// </summary>
        public static string ExportWarningDialogText {
            get {
                return ResourceManager.GetString("ExportWarningDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner.log.
        /// </summary>
        public static string FilenameAppLog {
            get {
                return ResourceManager.GetString("FilenameAppLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner_Keys.xml.
        /// </summary>
        public static string FilenameHotkeys {
            get {
                return ResourceManager.GetString("FilenameHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bytes.
        /// </summary>
        public static string FreeBytes {
            get {
                return ResourceManager.GetString("FreeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        public static string FreeGB {
            get {
                return ResourceManager.GetString("FreeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string FreeKB {
            get {
                return ResourceManager.GetString("FreeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        public static string FreeMB {
            get {
                return ResourceManager.GetString("FreeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} free of {1}.
        /// </summary>
        public static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click an action and press a key sequence.
        /// </summary>
        public static string HotKeyEditor_Directions {
            get {
                return ResourceManager.GetString("HotKeyEditor_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register {0} hot key [{1}].  {0} sequence set to None..
        /// </summary>
        public static string HotKeyNotRegistered {
            get {
                return ResourceManager.GetString("HotKeyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not unregister {0} hot key [{1}].
        /// </summary>
        public static string HotKeyNotUnregistered {
            get {
                return ResourceManager.GetString("HotKeyNotUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving hot keys: {0}.
        /// </summary>
        public static string HotKeysNotSaved {
            get {
                return ResourceManager.GetString("HotKeysNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Software.
        /// </summary>
        public static string I_ApplicationCompany {
            get {
                return ResourceManager.GetString("I_ApplicationCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner.
        /// </summary>
        public static string I_ApplicationProduct {
            get {
                return ResourceManager.GetString("I_ApplicationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner.
        /// </summary>
        public static string I_ApplicationTitle {
            get {
                return ResourceManager.GetString("I_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ituner.codeplex.com.
        /// </summary>
        public static string I_ApplicationURI {
            get {
                return ResourceManager.GetString("I_ApplicationURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _iTunerArchive.
        /// </summary>
        public static string I_ArchiveRootPath {
            get {
                return ResourceManager.GetString("I_ArchiveRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Formats&gt;
        ///  &lt;format FID=&quot;R_L_T&quot; pattern=&quot;{artist}\{album}\{title}&quot;/&gt;
        ///  &lt;format FID=&quot;R_LT&quot; pattern=&quot;{artist}\{album} - {title}&quot;/&gt;
        ///  &lt;format FID=&quot;RLT&quot; pattern=&quot;{artist} - {album} - {title}&quot;/&gt;
        ///  &lt;format FID=&quot;R_T&quot; pattern=&quot;{artist}\{title}&quot;/&gt;
        ///  &lt;format FID=&quot;L_R_T&quot; pattern=&quot;{album}\{artist}\{title}&quot;/&gt;
        ///  &lt;format FID=&quot;L_RT&quot; pattern=&quot;{album}\{artist} - {title}&quot;/&gt;
        ///  &lt;format FID=&quot;L_T&quot; pattern=&quot;{album}\{title}&quot;/&gt;
        ///  &lt;format FID=&quot;G_R_T&quot; pattern=&quot;{genre}\{artist}\{title}&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string I_FolderFormats {
            get {
                return ResourceManager.GetString("I_FolderFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddThh:mm:ssZ.
        /// </summary>
        public static string I_iTunesDttmFormat {
            get {
                return ResourceManager.GetString("I_iTunesDttmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=6UC9PK9LA92F8&amp;lc=US&amp;item_name=Support%20iTuner&amp;currency_code=USD&amp;bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted.
        /// </summary>
        public static string I_PayPalDonateUri {
            get {
                return ResourceManager.GetString("I_PayPalDonateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;header&gt;&lt;style&gt;BODY {{font-family:Calibri;font-size:10pt;background:#E2E2C1;margin:0 4 0 4;}}&lt;/style&gt;&lt;/header&gt;&lt;body&gt;{0}&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string I_ReleaseHtmFormat {
            get {
                return ResourceManager.GetString("I_ReleaseHtmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtworkScanner.
        /// </summary>
        public static string I_ScanArtwork {
            get {
                return ResourceManager.GetString("I_ScanArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtxDupScanner.
        /// </summary>
        public static string I_ScanContextDuplicates {
            get {
                return ResourceManager.GetString("I_ScanContextDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtxPhanScanner.
        /// </summary>
        public static string I_ScanContextPhantoms {
            get {
                return ResourceManager.GetString("I_ScanContextPhantoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateScanner.
        /// </summary>
        public static string I_ScanDuplicates {
            get {
                return ResourceManager.GetString("I_ScanDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyScanner.
        /// </summary>
        public static string I_ScanEmptyDirectories {
            get {
                return ResourceManager.GetString("I_ScanEmptyDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportScanner.
        /// </summary>
        public static string I_ScanExport {
            get {
                return ResourceManager.GetString("I_ScanExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileWatchScanner.
        /// </summary>
        public static string I_ScanFileWatch {
            get {
                return ResourceManager.GetString("I_ScanFileWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportPlaylistScanner.
        /// </summary>
        public static string I_ScanImportPlaylist {
            get {
                return ResourceManager.GetString("I_ScanImportPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InformationScanner.
        /// </summary>
        public static string I_ScanInformation {
            get {
                return ResourceManager.GetString("I_ScanInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializingScanner.
        /// </summary>
        public static string I_ScanInitialize {
            get {
                return ResourceManager.GetString("I_ScanInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaintenanceScanner.
        /// </summary>
        public static string I_ScanMaintenance {
            get {
                return ResourceManager.GetString("I_ScanMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhantomScanner.
        /// </summary>
        public static string I_ScanPhantoms {
            get {
                return ResourceManager.GetString("I_ScanPhantoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {36521039-4D94-40bd-9E7C-EBFB8B34ECE5}.
        /// </summary>
        public static string I_SingletonID {
            get {
                return ResourceManager.GetString("I_SingletonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ID3 {
            get {
                object obj = ResourceManager.GetObject("ID3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ImportCancelCaption {
            get {
                return ResourceManager.GetString("ImportCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import is in progress.
        ///Are you sure you want to cancel?.
        /// </summary>
        public static string ImportCancelText {
            get {
                return ResourceManager.GetString("ImportCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Playlist.
        /// </summary>
        public static string ImportPlaylistDialogTitle {
            get {
                return ResourceManager.GetString("ImportPlaylistDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of iTuner is not compatible with this version of iTunes.
        /// </summary>
        public static string IncompatibleAssemblies {
            get {
                return ResourceManager.GetString("IncompatibleAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes {0} is not compatible with iTuner&apos;s iTunesLib {1}.{2}.
        /// </summary>
        public static string IncompatibleVersions {
            get {
                return ResourceManager.GetString("IncompatibleVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize iTunes.  If an iTunes dialog is visible, dimiss it and restart iTuner..
        /// </summary>
        public static string InitializationFailure {
            get {
                return ResourceManager.GetString("InitializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon iTuner {
            get {
                object obj = ResourceManager.GetObject("iTuner", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon iTuner16 {
            get {
                object obj = ResourceManager.GetObject("iTuner16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon iTunes {
            get {
                object obj = ResourceManager.GetObject("iTunes", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon iTunes16 {
            get {
                object obj = ResourceManager.GetObject("iTunes16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Add to iTunes.
        /// </summary>
        public static string iTunesAutoDirectory {
            get {
                return ResourceManager.GetString("iTunesAutoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genius.
        /// </summary>
        public static string iTunesGeniusPlaylist {
            get {
                return ResourceManager.GetString("iTunesGeniusPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string iTunesLibrary {
            get {
                return ResourceManager.GetString("iTunesLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes is not installed on this computer..
        /// </summary>
        public static string iTunesMissing {
            get {
                return ResourceManager.GetString("iTunesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string iTunesMusicPlaylist {
            get {
                return ResourceManager.GetString("iTunesMusicPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Library {
            get {
                object obj = ResourceManager.GetObject("Library", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album...: {0} ({1}).
        /// </summary>
        public static string LyricsAlbumLine {
            get {
                return ResourceManager.GetString("LyricsAlbumLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist..: {0}.
        /// </summary>
        public static string LyricsArtistLine {
            get {
                return ResourceManager.GetString("LyricsArtistLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LyricsOff {
            get {
                object obj = ResourceManager.GetObject("LyricsOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LyricsOff1 {
            get {
                object obj = ResourceManager.GetObject("LyricsOff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LyricsOff2 {
            get {
                object obj = ResourceManager.GetObject("LyricsOff2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LyricsOff3 {
            get {
                object obj = ResourceManager.GetObject("LyricsOff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LyricsOff4 {
            get {
                object obj = ResourceManager.GetObject("LyricsOff4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LyricsOff5 {
            get {
                object obj = ResourceManager.GetObject("LyricsOff5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LyricsOn {
            get {
                object obj = ResourceManager.GetObject("LyricsOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating..: {0}.
        /// </summary>
        public static string LyricsRatingLine {
            get {
                return ResourceManager.GetString("LyricsRatingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title...: {0} ({1}).
        /// </summary>
        public static string LyricsTitleLine {
            get {
                return ResourceManager.GetString("LyricsTitleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About iTuner.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string MenuClean {
            get {
                return ResourceManager.GetString("MenuClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean album.
        /// </summary>
        public static string MenuCleanAlbum {
            get {
                return ResourceManager.GetString("MenuCleanAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string MenuCleanDuplicates {
            get {
                return ResourceManager.GetString("MenuCleanDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty directories.
        /// </summary>
        public static string MenuCleanEmpty {
            get {
                return ResourceManager.GetString("MenuCleanEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead tracks.
        /// </summary>
        public static string MenuCleanPhantoms {
            get {
                return ResourceManager.GetString("MenuCleanPhantoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean playlist.
        /// </summary>
        public static string MenuCleanPlaylist {
            get {
                return ResourceManager.GetString("MenuCleanPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit iTunes.
        /// </summary>
        public static string MenuExitiTunes {
            get {
                return ResourceManager.GetString("MenuExitiTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album....
        /// </summary>
        public static string MenuExportAlbum {
            get {
                return ResourceManager.GetString("MenuExportAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist....
        /// </summary>
        public static string MenuExportArtist {
            get {
                return ResourceManager.GetString("MenuExportArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist....
        /// </summary>
        public static string MenuExportPlaylist {
            get {
                return ResourceManager.GetString("MenuExportPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix....
        /// </summary>
        public static string MenuFix {
            get {
                return ResourceManager.GetString("MenuFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string MenuFixAlbum {
            get {
                return ResourceManager.GetString("MenuFixAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string MenuFixTrack {
            get {
                return ResourceManager.GetString("MenuFixTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import playlist....
        /// </summary>
        public static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string MenuNextTrack {
            get {
                return ResourceManager.GetString("MenuNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev Track.
        /// </summary>
        public static string MenuPrevTrack {
            get {
                return ResourceManager.GetString("MenuPrevTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string MenuShuffle {
            get {
                return ResourceManager.GetString("MenuShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync MP3 player....
        /// </summary>
        public static string MenuSync {
            get {
                return ResourceManager.GetString("MenuSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Mute {
            get {
                object obj = ResourceManager.GetObject("Mute", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon NextTrack {
            get {
                object obj = ResourceManager.GetObject("NextTrack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening URL.
        /// </summary>
        public static string NoBrowserCaption {
            get {
                return ResourceManager.GetString("NoBrowserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet browser not detected.  How do you survive?.
        /// </summary>
        public static string NoBrowserMessage {
            get {
                return ResourceManager.GetString("NoBrowserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to codeplex at this time.  Please try again later..
        /// </summary>
        public static string NoUpdateConnection {
            get {
                return ResourceManager.GetString("NoUpdateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the most recent version of iTuner.
        /// </summary>
        public static string NoUpgrades {
            get {
                return ResourceManager.GetString("NoUpgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner Options.
        /// </summary>
        public static string OptionsDialog_Title {
            get {
                return ResourceManager.GetString("OptionsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PauseActive {
            get {
                object obj = ResourceManager.GetObject("PauseActive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Phantom {
            get {
                object obj = ResourceManager.GetObject("Phantom", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PlayActive {
            get {
                object obj = ResourceManager.GetObject("PlayActive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Playlist {
            get {
                object obj = ResourceManager.GetObject("Playlist", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PlaylistFolder {
            get {
                object obj = ResourceManager.GetObject("PlaylistFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genius.
        /// </summary>
        public static string PlaylistGenius {
            get {
                return ResourceManager.GetString("PlaylistGenius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string PlaylistMovies {
            get {
                return ResourceManager.GetString("PlaylistMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts.
        /// </summary>
        public static string PlaylistPodcasts {
            get {
                return ResourceManager.GetString("PlaylistPodcasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PlaylistPurchased {
            get {
                object obj = ResourceManager.GetObject("PlaylistPurchased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string PlaylistRadio {
            get {
                return ResourceManager.GetString("PlaylistRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PlaylistSmart {
            get {
                object obj = ResourceManager.GetObject("PlaylistSmart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes Store.
        /// </summary>
        public static string PlaylistStore {
            get {
                return ResourceManager.GetString("PlaylistStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string PlaylistTVShows {
            get {
                return ResourceManager.GetString("PlaylistTVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PlaylistUser {
            get {
                object obj = ResourceManager.GetObject("PlaylistUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PrevTrack {
            get {
                object obj = ResourceManager.GetObject("PrevTrack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected AAC.
        /// </summary>
        public static string ProtectedAAC {
            get {
                return ResourceManager.GetString("ProtectedAAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Star.
        /// </summary>
        public static string RatingControl_1Star {
            get {
                return ResourceManager.GetString("RatingControl_1Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Stars.
        /// </summary>
        public static string RatingControl_2Stars {
            get {
                return ResourceManager.GetString("RatingControl_2Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Stars.
        /// </summary>
        public static string RatingControl_3Stars {
            get {
                return ResourceManager.GetString("RatingControl_3Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Stars.
        /// </summary>
        public static string RatingControl_4Stars {
            get {
                return ResourceManager.GetString("RatingControl_4Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Stars.
        /// </summary>
        public static string RatingControl_5Stars {
            get {
                return ResourceManager.GetString("RatingControl_5Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Dups.
        /// </summary>
        public static string ScanAlbumDups {
            get {
                return ResourceManager.GetString("ScanAlbumDups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Dead.
        /// </summary>
        public static string ScanAlbumPhantoms {
            get {
                return ResourceManager.GetString("ScanAlbumPhantoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Scanner.
        /// </summary>
        public static string ScanArtwork {
            get {
                return ResourceManager.GetString("ScanArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dup Scanner.
        /// </summary>
        public static string ScanDuplicates {
            get {
                return ResourceManager.GetString("ScanDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dup Album.
        /// </summary>
        public static string ScanDuplicatesByAlbum {
            get {
                return ResourceManager.GetString("ScanDuplicatesByAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dup Playlist.
        /// </summary>
        public static string ScanDuplicatesByPlaylist {
            get {
                return ResourceManager.GetString("ScanDuplicatesByPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Scanner.
        /// </summary>
        public static string ScanEmpty {
            get {
                return ResourceManager.GetString("ScanEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter.
        /// </summary>
        public static string ScanExport {
            get {
                return ResourceManager.GetString("ScanExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Scanner.
        /// </summary>
        public static string ScanFileWatch {
            get {
                return ResourceManager.GetString("ScanFileWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Playlist.
        /// </summary>
        public static string ScanImportPlaylist {
            get {
                return ResourceManager.GetString("ScanImportPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Info.
        /// </summary>
        public static string ScanInformation {
            get {
                return ResourceManager.GetString("ScanInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        public static string ScanInitialize {
            get {
                return ResourceManager.GetString("ScanInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain DB.
        /// </summary>
        public static string ScanMaintenance {
            get {
                return ResourceManager.GetString("ScanMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan for and remove duplicate tracks within a single album. Duplicates are not deleted but rather moved to a special iTuner archive directory..
        /// </summary>
        public static string ScannerOptions_Archive {
            get {
                return ResourceManager.GetString("ScannerOptions_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive duplicates.
        /// </summary>
        public static string ScannerOptions_ArchiveTitle {
            get {
                return ResourceManager.GetString("ScannerOptions_ArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch the artwork published with each album.  This is part of the Clean function.  Images are stored separately by iTunes in a proprietary format..
        /// </summary>
        public static string ScannerOptions_Artwork {
            get {
                return ResourceManager.GetString("ScannerOptions_Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album artwork.
        /// </summary>
        public static string ScannerOptions_ArtworkTitle {
            get {
                return ResourceManager.GetString("ScannerOptions_ArtworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The iTuner Librarian automatically runs each of these maintenance tasks as tracks are played. The automated scanners process a single album at a time..
        /// </summary>
        public static string ScannerOptions_Description {
            get {
                return ResourceManager.GetString("ScannerOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan for and delete dead tracks.  These are entries in iTunes for which no corresponding media file exists..
        /// </summary>
        public static string ScannerOptions_Phantom {
            get {
                return ResourceManager.GetString("ScannerOptions_Phantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove dead tracks.
        /// </summary>
        public static string ScannerOptions_PhantomTitle {
            get {
                return ResourceManager.GetString("ScannerOptions_PhantomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monitor changes made to the iTunes media folder on your hard drive and synchronizes those changes with the iTunes Library.  This includes automated import of new files, deleting files, and renaming files..
        /// </summary>
        public static string ScannerOptions_Watch {
            get {
                return ResourceManager.GetString("ScannerOptions_Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch files.
        /// </summary>
        public static string ScannerOptions_WatchTitle {
            get {
                return ResourceManager.GetString("ScannerOptions_WatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Album.
        /// </summary>
        public static string ScanPhantomByAlbum {
            get {
                return ResourceManager.GetString("ScanPhantomByAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Playlist.
        /// </summary>
        public static string ScanPhantomByPlaylist {
            get {
                return ResourceManager.GetString("ScanPhantomByPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Scanner.
        /// </summary>
        public static string ScanPhantoms {
            get {
                return ResourceManager.GetString("ScanPhantoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizer.
        /// </summary>
        public static string ScanSynchronize {
            get {
                return ResourceManager.GetString("ScanSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Shuffle {
            get {
                object obj = ResourceManager.GetObject("Shuffle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running.
        /// </summary>
        public static string SingletonMessage {
            get {
                return ResourceManager.GetString("SingletonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting iTunes....
        /// </summary>
        public static string SplashWindow_Starting {
            get {
                return ResourceManager.GetString("SplashWindow_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Synchronization.
        /// </summary>
        public static string SyncCancelCaption {
            get {
                return ResourceManager.GetString("SyncCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization is in progress.
        ///Are you sure you want to cancel?.
        /// </summary>
        public static string SyncCancelText {
            get {
                return ResourceManager.GetString("SyncCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No USB MP3 devices found.  Connect a device now to continue or click Cancel to quit....
        /// </summary>
        public static string SyncDialog_NoUSB {
            get {
                return ResourceManager.GetString("SyncDialog_NoUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 0 tracks.
        /// </summary>
        public static string SyncDialog_Select0 {
            get {
                return ResourceManager.GetString("SyncDialog_Select0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string SyncDialog_SyncButton {
            get {
                return ResourceManager.GetString("SyncDialog_SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        public static string SyncDialog_Synchronizing {
            get {
                return ResourceManager.GetString("SyncDialog_Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTuner MP3 Synchronize.
        /// </summary>
        public static string SyncDialog_Title {
            get {
                return ResourceManager.GetString("SyncDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string SyncWarningCaption {
            get {
                return ResourceManager.GetString("SyncWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all files on the USB device under {0} that are not part of the selected playlists.
        ///
        ///Click OK to confirm and continue....
        /// </summary>
        public static string SyncWarningText {
            get {
                return ResourceManager.GetString("SyncWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change options.
        /// </summary>
        public static string TaskPanel_ChangeOptions {
            get {
                return ResourceManager.GetString("TaskPanel_ChangeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change view.
        /// </summary>
        public static string TaskPanel_ChangeView {
            get {
                return ResourceManager.GetString("TaskPanel_ChangeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current tasks.
        /// </summary>
        public static string TaskPanel_NoTasks {
            get {
                return ResourceManager.GetString("TaskPanel_NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set hot keys.
        /// </summary>
        public static string TaskPanel_SetHotKeys {
            get {
                return ResourceManager.GetString("TaskPanel_SetHotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show iTunes.
        /// </summary>
        public static string TaskPanel_ShowiTunes {
            get {
                return ResourceManager.GetString("TaskPanel_ShowiTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lyrics.
        /// </summary>
        public static string TaskPanel_ShowLyrics {
            get {
                return ResourceManager.GetString("TaskPanel_ShowLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle shuffle.
        /// </summary>
        public static string TaskPanel_ToggleShuffle {
            get {
                return ResourceManager.GetString("TaskPanel_ToggleShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play position.
        /// </summary>
        public static string TimeControl_PlayPosition {
            get {
                return ResourceManager.GetString("TimeControl_PlayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Track {
            get {
                object obj = ResourceManager.GetObject("Track", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} tracks.
        /// </summary>
        public static string TrackCountPlural {
            get {
                return ResourceManager.GetString("TrackCountPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} track.
        /// </summary>
        public static string TrackCountSingular {
            get {
                return ResourceManager.GetString("TrackCountSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album:.
        /// </summary>
        public static string TrackPanel_Album {
            get {
                return ResourceManager.GetString("TrackPanel_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist:.
        /// </summary>
        public static string TrackPanel_Artist {
            get {
                return ResourceManager.GetString("TrackPanel_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change view.
        /// </summary>
        public static string TrackPanel_ChangeView {
            get {
                return ResourceManager.GetString("TrackPanel_ChangeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        public static string TrackPanel_Genre {
            get {
                return ResourceManager.GetString("TrackPanel_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind:.
        /// </summary>
        public static string TrackPanel_Kind {
            get {
                return ResourceManager.GetString("TrackPanel_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string TrackPanel_Length {
            get {
                return ResourceManager.GetString("TrackPanel_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string TrackPanel_Location {
            get {
                return ResourceManager.GetString("TrackPanel_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string TrackPanel_Rating {
            get {
                return ResourceManager.GetString("TrackPanel_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TrackPanel_Title {
            get {
                return ResourceManager.GetString("TrackPanel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track:.
        /// </summary>
        public static string TrackPanel_Track {
            get {
                return ResourceManager.GetString("TrackPanel_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        public static string TrackPanel_Year {
            get {
                return ResourceManager.GetString("TrackPanel_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the iTuner is available.  It is recommended that you always run the most recent version, as this often has critical bug fixes and improved features.  Please consider the Change History shown below and click the Upgrade button when ready..
        /// </summary>
        public static string UpgradeWindow_Directions {
            get {
                return ResourceManager.GetString("UpgradeWindow_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        public static string UpgradeWindow_ReleaseNotes {
            get {
                return ResourceManager.GetString("UpgradeWindow_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit upgrade web page.
        /// </summary>
        public static string UpgradeWindow_Visit {
            get {
                return ResourceManager.GetString("UpgradeWindow_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}).
        /// </summary>
        public static string UsbDescription {
            get {
                return ResourceManager.GetString("UsbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}) {3}.
        /// </summary>
        public static string UsbLongDescription {
            get {
                return ResourceManager.GetString("UsbLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}.{2}.{3}.
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max volume.
        /// </summary>
        public static string VolumeControl_MaxVolume {
            get {
                return ResourceManager.GetString("VolumeControl_MaxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min volume.
        /// </summary>
        public static string VolumeControl_MinVolume {
            get {
                return ResourceManager.GetString("VolumeControl_MinVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume ({0}).
        /// </summary>
        public static string VolumeSettingFormat {
            get {
                return ResourceManager.GetString("VolumeSettingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
